786ms/urls.py
from django.conf.urls import  include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

admin.autodiscover()


handler404 = 'home.views.handler404'
handler500 = 'home.views.handler500'
handler403 = 'home.views.handler403'
handler400 = 'home.views.handler400'

urlpatterns = [
	url(r'',include('home.urls')),
	 url(r'career/',include('career.urls')),
     url(r'student/',include('students.urls')),
	 url(r'shops/', include('shops.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_ROOT, document_root=settings.MEDIA_URL)

home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$',views.index,name="index"),
	url(r'#(?P<tag>[a-z]+)/$',views.index,name="index"),
]

shops/urls.py
from django.conf.urls import include, url
from . import views
urlpatterns = [
	url(r'^$',views.listShops,name="listShops"),
    url(r'^(?P<shop_id>[\d+])$',views.shopSummary,name="ShopSummary"),
    url(r'^(?P<shop_id>[\d+])/(?P<cycle>[\w]+)$',views.shopSummary,name="ShopSummary"),
    url(r'^(?P<shop_id>[\d+])/(?P<cycle>[\w]+)/(?P<delta>[\d]+)$',views.shopSummary,name="ShopSummary"),
]

shops/models.py
from __future__ import unicode_literals

from django.db import models

class Shop(models.Model):
    name=models.CharField(max_length=100)
    description=models.CharField(max_length=500)
    location=models.CharField(max_length=50)

class SaleEntry(models.Model):
    shop=models.ForeignKey(Shop)
    amount=models.FloatField(default=0.0)
    description=models.CharField(max_length=100)
    notes=models.CharField(max_length=500)
    timestamp=models.DateTimeField(auto_now=True,blank=False)
    class Meta:
        ordering = ['-timestamp']

shops/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import *
@login_required(login_url='/student/manager/')
def listShops(request):
    data={}
    try:
        data['shops']=Shop.objects.all()
    except Exception as e:
        data['error']=str(e)
        return render(request,'error.html',data)
    return render(request,'shops/shops.html',data)

@login_required(login_url='/student/manager/')
def shopSummary(request,shop_id):
    return shopSummary(request,shop_id,'daily','0')

@login_required(login_url='/student/manager/')
def shopSummary(request,shop_id,cycle='all'):
    return shopSummary(request,shop_id,cycle,'0')

@login_required(login_url='/student/manager/')
def shopSummary(request,shop_id,cycle='daily',delta='0'):
    data={}
    try:
        shop_id=int(shop_id)
        delta=int(delta)
        #TODO: send items per cycle
        if cycle=='daily':
            pass
        elif cycle=='monthly':
            pass
        elif cycle=='yearly':
            pass
        elif cycle=='all':
            pass
        else:
            raise Exception('Invalid Url cycle not valid')
        data['cycle']=cycle
        data['delta']=delta
        data['shop']=Shop.objects.get(pk=shop_id)
    except Exception as e:
        data['error']=str(e)
        print('error'+str(e))
        return render(request,'error.html',data)
    return render(request,'shops/shop_detail.html',data);

shops/templates/shops/shop_detail.html
{% extends 'base.html'%} {% block body_block%}
<div class="container">
    {%if shop%}
    <br/>
    <div class="row">
        <a href="/shops/{{shop.id}}/daily/0" class="btn {%if cycle == 'daily' %}btn-success{%else%}btn-primary{%endif%}">Daily</a>
        <a href="/shops/{{shop.id}}/monthly/0" class="btn {%if cycle == 'monthly'%}btn-success{%else%}btn-primary{%endif%}">Monthly</a>
        <a href="/shops/{{shop.id}}/yearly/0" class="btn {%if cycle == 'yearly'%}btn-success{%else%}btn-primary{%endif%}">Yearly</a>
        <a href="/shops/{{shop.id}}/all" class="btn {%if cycle == 'all'%}btn-success{%else%}btn-primary{%endif%}">All</a>
    </div>

    <div>
        <h3>{{shop.name}}<small>{{shop.location}}</small></h3>
        <br>
        <h4></h4>
        <table class="table">
            <tr>
                <th>Description</th>
                <th>Amount</th>
                <th>Notes</th>
                <th>Datetime</th>
            </tr>
            {%for item in shop.saleentry_set.all%}
            <tr>
                <td>{{item.description}}</td>
                <td>{{item.amount}}</td>
                <td>{{item.notes}}</td>
                <td>{{item.timestamp|date:'d, M Y H:i:s'}}</td>
            </tr>
            {%endfor%}
        </table>
        <br>
        <div class="row">
            <div class="col-xs-2">
                <a class="btn btn-primary" href="/shops/{{shop.id}}/{{cycle}}/{{delta|add:-1}}">Previous</a>
            </div>
            <div class="col-xs-2 col-xs-offset-8 ">
                <a class="btn btn-primary" href="/shops/{{shop.id}}/{{cycle}}/{{delta|add:1}}">Next</a>
            </div>
        </div>
    </div>
    {%else%}
    <div class="alert alert-danger">No shop received</div>
    {%endif%}

</div>
{% endblock %}

shops/templates/shops/shops.html
{% extends 'base.html'%} {% block body_block%}
<div class="container">
    {%if shops%}
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Location</th>
        </tr>
        {%for shop in shops%}
        <tr>
            <td><a href="/shops/{{shop.id}}">{{shop.name}}</a></td>
            <td>{{shop.description}}</td>
            <td>{{shop.location}}</td>
        </tr>
        {%endfor%}
    </table>
    {%else%}
    <div class="slert alert-warning">No shops registered.</div>
    {%endif%}
    <div class="btn btn-primary">Add Shop</div>
</div>
{% endblock %}